### ISSUE TITLE
"Can't update() without base config" if installed via setup.py

### ISSUE THREAD

**Issue by bobpaul** [tulir/mautrix-hangouts#14]
If I follow the wiki instructions and use a virtual env, then everything works if I launch like this:

```
$ python -m mautrix_hangouts -c /etc/synapse/mautrix-hangouts/config.yaml -r /etc/synapse/mautrix-hangouts/registration.yaml
```

But if I install locally with setup.py, then running `mautrix-hangouts` complains if I don't give the `-b` option.

```
$ mautrix-hangouts -c /etc/synapse/mautrix-hangouts/config.yaml -r /etc/synapse/mautrix-hangouts/registration.yaml                                          Traceback (most recent call last):                                                                                                                                                            
  File "/usr/bin/mautrix-hangouts", line 11, in <module>                                                                                                                                      
    load_entry_point('mautrix-hangouts==0.1.0.dev7+dev.1241db9b', 'console_scripts', 'mautrix-hangouts')()                                                                                      File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point                                                                                            
    return get_distribution(dist).load_entry_point(group, name)                                                                                                                               
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point                                                                                           
    return ep.load()                                                                                                                                                                            File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load                                                                                                       
    return self.resolve()                                                                                                                                                                     
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve                                                                                                        module = __import__(self.module_name, fromlist=['__name__'], level=0)                                                                                                                       File "/usr/lib/python3.8/site-packages/mautrix_hangouts/__main__.py", line 78, in <module>                                                                                                      HangoutsBridge().run()                                                                                                                                                                      File "/usr/lib/python3.8/site-packages/mautrix/bridge/bridge.py", line 83, in run                                                                                                           
    self._prepare()                                                                                                                                                                             File "/usr/lib/python3.8/site-packages/mautrix/bridge/bridge.py", line 105, in _prepare                                                                                                         self.prepare_config(self.args.config, self.args.registration, self.args.base_config)                                                                                                      
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/bridge.py", line 128, in prepare_config                                                                                                   self.config.update()                                                                                                                                                                      
  File "/usr/lib/python3.8/site-packages/mautrix/util/config.py", line 151, in update                                                                                                         
    raise ValueError("Can't update() without base config")                                                                                                                                    
ValueError: Can't update() without base config
```

Works fine if I provide `-b` and point at the example config:

```
$ mautrix-hangouts -c /etc/synapse/mautrix-hangouts/config.yaml -r /etc/synapse/mautrix-hangouts/registration.yaml -b /usr/example-config.yaml
```

**Comment by tulir** [comment]
That seems to be working as expected. I should improve the error message though: tulir/mautrix-python#17

**Comment by bobpaul** [comment]
Why is `-b` optional when run as `python -m mautrix_hangouts` but required when run as `mautrix-hangouts`?
