### ISSUE TITLE
Causes tons and tons of errors in Synapse log

### ISSUE THREAD

**Issue by jgoerzen** [tulir/mautrix-hangouts#18]
I use both this and mautrix-facebook, and both cause this behavior.  I get multiple of these each second in my Synapse logs:

```
Apr 12 18:50:13 matrix matrix-synapse[18641]: 2020-04-12 23:50:13,529 - synapse.http.server - 110 - ERROR - GET-129521 - Failed handle request via 'SyncRestServlet': <XForwardedForRequest at 0x7f182d5e6bd0 method='GET' uri='/_matrix/client/r0/sync?access_token=<redacted>&timeout=30000&filter=%7B%22presence%22:%7B%22not_types%22:%5B%22*%22%5D%7D,%22account_data%22:%7B%22types%22:%5B%22*%22%5D%7D,%22room%22:%7B%22ephemeral%22:%7B%22not_types%22:%5B%22*%22%5D,%22lazy_load_members%22:false,%22include_redundant_members%22:false%7D,%22include_leave%22:false,%22state%22:%7B%22not_types%22:%5B%22*%22%5D,%22lazy_load_members%22:false,%22include_redundant_members%22:false%7D,%22timeline%22:%7B%22not_types%22:%5B%22*%22%5D,%22lazy_load_members%22:false,%22include_redundant_members%22:false%7D,%22account_data%22:%7B%22not_types%22:%5B%22*%22%5D,%22lazy_load_members%22:false,%22include_redundant_members%22:false%7D%7D%7D' clientproto='HTTP/1.1' site=8008>
Apr 12 18:50:13 matrix matrix-synapse[18641]: Traceback (most recent call last):
Apr 12 18:50:13 matrix matrix-synapse[18641]: File "/usr/local/lib/python3.7/site-packages/synapse/http/server.py", line 78, in wrapped_request_handler
Apr 12 18:50:13 matrix matrix-synapse[18641]: await h(self, request)
Apr 12 18:50:13 matrix matrix-synapse[18641]: File "/usr/local/lib/python3.7/site-packages/synapse/http/server.py", line 331, in _async_render
Apr 12 18:50:13 matrix matrix-synapse[18641]: callback_return = await callback_return
Apr 12 18:50:13 matrix matrix-synapse[18641]: File "/usr/local/lib/python3.7/site-packages/synapse/rest/client/v2_alpha/sync.py", line 178, in on_GET
Apr 12 18:50:13 matrix matrix-synapse[18641]: full_state=full_state,
Apr 12 18:50:13 matrix matrix-synapse[18641]: File "/usr/local/lib/python3.7/site-packages/synapse/handlers/sync.py", line 286, in wait_for_sync_for_user
Apr 12 18:50:13 matrix matrix-synapse[18641]: full_state,
Apr 12 18:50:13 matrix matrix-synapse[18641]: File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
Apr 12 18:50:13 matrix matrix-synapse[18641]: result = g.send(result)
Apr 12 18:50:13 matrix matrix-synapse[18641]: File "/usr/local/lib/python3.7/site-packages/synapse/handlers/sync.py", line 312, in _wait_for_sync_for_user
Apr 12 18:50:13 matrix matrix-synapse[18641]: sync_config, since_token, full_state=full_state
Apr 12 18:50:13 matrix matrix-synapse[18641]: File "/usr/local/lib/python3.7/site-packages/synapse/handlers/sync.py", line 343, in current_sync_for_user
Apr 12 18:50:13 matrix matrix-synapse[18641]: return await self.generate_sync_result(sync_config, since_token, full_state)
Apr 12 18:50:13 matrix matrix-synapse[18641]: File "/usr/local/lib/python3.7/site-packages/synapse/handlers/sync.py", line 982, in generate_sync_result
Apr 12 18:50:13 matrix matrix-synapse[18641]: raise NotImplementedError()
Apr 12 18:50:13 matrix matrix-synapse[18641]: NotImplementedError
```

When I shut down the Facebook and Hangouts bridges, these go away.  Start them up again, and they return.

A comment in the Synapse code that appears to be relevant directs to https://github.com/matrix-org/matrix-doc/issues/1144

**Comment by bobpaul** [comment]
What version of synapse are you running? What version (which commit) of mautrix-hangouts?

**Comment by jgoerzen** [comment]
Hi,

I am using the Ansible build from https://github.com/spantaleev/matrix-docker-ansible-deploy which in turn is using the Docker image from dock.mau.dev/tulir/mautrix-hangouts:latest .  I am unsure how to tease a git commit out of that.  Synapse is 1.12.3.  Thanks!

**Comment by tulir** [comment]
https://github.com/tulir/mautrix-telegram/wiki/End‐to‐bridge-encryption
