### ISSUE TITLE
Received images no longer appearing

### ISSUE THREAD

**Issue by meyerrj** [tulir/mautrix-hangouts#19]
Received images (sent by others) through hangouts are no longer appearing in Riot/Matrix clients.

Images sent through Riot/Matrix are successfully sending as expected.

**Comment by erdnaxeli** [comment]
The error is the following
```
mautrix-hangouts    | [2020-04-18 08:51:51,615] [DEBUG@mau.as.api.@hangouts_102111775594222325608:cervoi.se] PUT /_matrix/client/r0/rooms/%21YkrdxzBHvFFSoUvmhx%3Acervoi.se/send/m.room.message/1091587199911615 {"b
ody": "2020-04-18-Chantier2bis.jpg", "url": "mxc://cervoi.se/yCXSyPeKxFMIDDfCVlESEvQd", "info": {"mimetype": "image/jpeg", "size": 370134}}
mautrix-hangouts    | [2020-04-18 08:51:51,621] [ERROR@mau.user.@erdnaxeli:cervoi.se] Exception in event handler
mautrix-hangouts    | Traceback (most recent call last):
mautrix-hangouts    |   File "/opt/mautrix-hangouts/mautrix_hangouts/user.py", line 233, in try_proxy
mautrix-hangouts    |     await method(*args, **kwargs)
mautrix-hangouts    |   File "/opt/mautrix-hangouts/mautrix_hangouts/user.py", line 274, in on_event
mautrix-hangouts    |     await portal.handle_hangouts_message(self, sender, event)
mautrix-hangouts    |   File "/opt/mautrix-hangouts/mautrix_hangouts/portal.py", line 445, in handle_hangouts_message
mautrix-hangouts    |     event_id = await self.process_hangouts_attachments(event, intent)
mautrix-hangouts    |   File "/opt/mautrix-hangouts/mautrix_hangouts/portal.py", line 492, in process_hangouts_attachments
mautrix-hangouts    |     return await self._send_message(intent, content)
mautrix-hangouts    |   File "/opt/mautrix-hangouts/mautrix_hangouts/portal.py", line 422, in _send_message
mautrix-hangouts    |     return await intent.send_message_event(self.mxid, event_type, content, **kwargs)
mautrix-hangouts    |   File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 87, in wrapper
mautrix-hangouts    |     return await __method(*args, **kwargs)
mautrix-hangouts    |   File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 289, in send_message_event
mautrix-hangouts    |     return await super().send_message_event(room_id, event_type, content, **kwargs)
mautrix-hangouts    |   File "/usr/lib/python3.8/site-packages/mautrix/client/api/events.py", line 294, in send_message_event
mautrix-hangouts    |     resp = await self.api.request(Method.PUT, url, content, **kwargs)
mautrix-hangouts    |   File "/usr/lib/python3.8/site-packages/mautrix/api/http.py", line 205, in request
mautrix-hangouts    |     return await self._send(method, endpoint, content, query_params, headers or {})
mautrix-hangouts    |   File "/usr/lib/python3.8/site-packages/mautrix/api/http.py", line 144, in _send
mautrix-hangouts    |     raise make_request_error(http_status=response.status,
mautrix-hangouts    | mautrix.errors.request.MUnknown: 'msgtype' not in content

```
