### ISSUE TITLE
Bridge fails to start

### ISSUE THREAD

**Issue by Scorcerer** [tulir/mautrix-hangouts#24]
Hi,
after update, i get the following error:

```
systemd[1]: Started mautrix-hangouts.
python[322853]: Traceback (most recent call last):
python[322853]:   File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
python[322853]:     return _run_code(code, main_globals, None,
python[322853]:   File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
python[322853]:     exec(code, run_globals)
python[322853]:   File "/var/lib/synapse/mautrix-hangouts/mautrix_hangouts/__main__.py", line 22, in <module>
python[322853]:     from .sqlstatestore import SQLStateStore
python[322853]:   File "/var/lib/synapse/mautrix-hangouts/mautrix_hangouts/sqlstatestore.py", line 19, in <module>
python[322853]:     from . import puppet as pu
python[322853]:   File "/var/lib/synapse/mautrix-hangouts/mautrix_hangouts/puppet.py", line 31, in <module>
python[322853]:     from . import user as u, portal as p, matrix as m
python[322853]:   File "/var/lib/synapse/mautrix-hangouts/mautrix_hangouts/user.py", line 37, in <module>
python[322853]:     from .util.hangups_try_auth import try_auth, TryAuthResp
python[322853]:   File "/var/lib/synapse/mautrix-hangouts/mautrix_hangouts/util/__init__.py", line 1, in <module>
python[322853]:     from .color_log import ColorFormatter
python[322853]:   File "/var/lib/synapse/mautrix-hangouts/mautrix_hangouts/util/color_log.py", line 16, in <module>
python[322853]:     from mautrix.util.logging.color import ColorFormatter as BaseColorFormatter, PREFIX, RESET
python[322853]: ModuleNotFoundError: No module named 'mautrix.util.logging'
systemd[1]: mautrix-hangouts.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: mautrix-hangouts.service: Failed with result 'exit-code'.
```

This is revision 29e5705dbe5ad9f0101a335a67fab53261a53033, after following the usual update steps.
Any idea what's missing?

**Comment by Scorcerer** [comment]
Ah, I've found it, commenting out "file:" section in "handlers" fixed it :)
