### ISSUE TITLE
Problems during initial backfill

### ISSUE THREAD

**Issue by hooger** [tulir/mautrix-hangouts#27]
The following issue is a summary of my "Wall of text"-like messages in the support room.

I recreated the bridge and do a login. Automatic login had some issue, I falled back to manual login, which was successful. After that in Riot a single room was created, corresponding to my latest contact, my user invited and no message was backfilled. Initial backfill was enabled, 5 room and 75 messages each, should've been backfilled.

In bridge log I saw that connection was indeed successful, all my contacts were recognized, the configuration file should be good, as the log says `Server returned 5 conversations` as it should, than starts backfilling the first user (the latest), with the following query:
```
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]: request_header {
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]:   client_version {
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]:     client_id: CLIENT_ID_WEB_HANGOUTS
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]:     major_version: "hangups-0.4.10"
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]:   }
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]:   client_identifier {
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]:     resource: "lcsw_hangouts_OBFUSCATE-ID"
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]:   }
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]:   language_code: "en"
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]: }
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]: conversation_spec {
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]:   conversation_id {
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]:     id: "OBFUSCATE-ID"
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]:   }
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]: }
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]: include_conversation_metadata: false
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]: include_event: true
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]: max_events_per_conversation: 75

```
after that a really long response arrives, with the 75 messages. It also seems good. After that the following query is sent:

```
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]: [2020-06-29 09:31:18,819] [DEBUG@hangups.client] Sending Protocol Buffer request conversations/getconversation:
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]: request_header {
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]:   client_version {
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]:     client_id: CLIENT_ID_WEB_HANGOUTS
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]:     major_version: "hangups-0.4.10"
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]:   }
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]:   client_identifier {
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]:     resource: "lcsw_hangouts_ID"
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]:   }
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]:   language_code: "en"
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]: }
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]: conversation_spec {
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]:   conversation_id {
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]:     id: "ID"
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]:   }
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]: }
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]: include_conversation_metadata: false
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]: include_event: true
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]: max_events_per_conversation: 0
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]: event_continuation_token {
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]:   storage_continuation_token: " TOKEN
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]:   event_timestamp: 1589825871012680
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]: }
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]: [2020-06-29 09:31:18,822] [DEBUG@hangups.http_utils] Sending request post https://clients6.google.com/chat/v1/conversations/getconversation:
Jun 29 11:31:18 raspberrypi matrix-mautrix-hangouts[18773]: b'LONGSTRING
Jun 29 11:31:19 raspberrypi matrix-mautrix-hangouts[18773]: [2020-06-29 09:31:19,050] [DEBUG@hangups.http_utils] Received response 200 OK:
Jun 29 11:31:19 raspberrypi matrix-mautrix-hangouts[18773]: b'LONGSTRING'
```
and the server response is
```
Jun 29 11:31:19 raspberrypi matrix-mautrix-hangouts[18773]: [2020-06-29 09:31:19,052] [DEBUG@hangups.client] Received Protocol Buffer response:
Jun 29 11:31:19 raspberrypi matrix-mautrix-hangouts[18773]: response_header {
Jun 29 11:31:19 raspberrypi matrix-mautrix-hangouts[18773]:   status: RESPONSE_STATUS_OK
Jun 29 11:31:19 raspberrypi matrix-mautrix-hangouts[18773]:   current_server_time: 1593423078910000
Jun 29 11:31:19 raspberrypi matrix-mautrix-hangouts[18773]: }
Jun 29 11:31:19 raspberrypi matrix-mautrix-hangouts[18773]: conversation_state {
Jun 29 11:31:19 raspberrypi matrix-mautrix-hangouts[18773]:   conversation_id {
Jun 29 11:31:19 raspberrypi matrix-mautrix-hangouts[18773]:     id: "ID"
Jun 29 11:31:19 raspberrypi matrix-mautrix-hangouts[18773]:   }
Jun 29 11:31:19 raspberrypi matrix-mautrix-hangouts[18773]: }

```
This query-response is happening for about 3 hours now, in an infinte loop, and nothing in Riot appeared.

My idea was, that somehow the bridge sees that 75 messages out of the querried 75 is already arrived, and tries to querry the last 0 messages, but it does not give the expected results so keeps on trying. My idea is based on the fact that in the infinte query there is an `event_continuation_token`.

To check it I also tried it first with a 100 messages, than with 50 messages. Neither helped. I tried restarting the bridge with and without leaving that particular room. Nothing helped.

Any idea what my go wrong?

**Comment by hooger** [comment]
So it was running since I posted the original issue, about 3 hours ago. After a while one request got an `unexpected error`, after which backfilling stopped and started to sync the next room. Same is happening with the next room. Maybe it helps. :crossed_fingers: 
The log for the last request-response following:
```
Jun 29 18:20:19 raspberrypi matrix-mautrix-hangouts[8019]: [2020-06-29 16:20:19,417] [DEBUG@hangups.client] Sending Protocol Buffer request conversations/getconversation:
Jun 29 18:20:19 raspberrypi matrix-mautrix-hangouts[8019]: request_header {
Jun 29 18:20:19 raspberrypi matrix-mautrix-hangouts[8019]:   client_version {
Jun 29 18:20:19 raspberrypi matrix-mautrix-hangouts[8019]:     client_id: CLIENT_ID_WEB_HANGOUTS
Jun 29 18:20:19 raspberrypi matrix-mautrix-hangouts[8019]:     major_version: "hangups-0.4.10"
Jun 29 18:20:19 raspberrypi matrix-mautrix-hangouts[8019]:   }
Jun 29 18:20:19 raspberrypi matrix-mautrix-hangouts[8019]:   client_identifier {
Jun 29 18:20:19 raspberrypi matrix-mautrix-hangouts[8019]:     resource: "TOKEN/ID"
Jun 29 18:20:19 raspberrypi matrix-mautrix-hangouts[8019]:   }
Jun 29 18:20:19 raspberrypi matrix-mautrix-hangouts[8019]:   language_code: "en"
Jun 29 18:20:19 raspberrypi matrix-mautrix-hangouts[8019]: }
Jun 29 18:20:19 raspberrypi matrix-mautrix-hangouts[8019]: conversation_spec {
Jun 29 18:20:19 raspberrypi matrix-mautrix-hangouts[8019]:   conversation_id {
Jun 29 18:20:19 raspberrypi matrix-mautrix-hangouts[8019]:     id: "TOKEN/ID"
Jun 29 18:20:19 raspberrypi matrix-mautrix-hangouts[8019]:   }
Jun 29 18:20:19 raspberrypi matrix-mautrix-hangouts[8019]: }
Jun 29 18:20:19 raspberrypi matrix-mautrix-hangouts[8019]: include_conversation_metadata: false
Jun 29 18:20:19 raspberrypi matrix-mautrix-hangouts[8019]: include_event: true
Jun 29 18:20:19 raspberrypi matrix-mautrix-hangouts[8019]: max_events_per_conversation: 0
Jun 29 18:20:19 raspberrypi matrix-mautrix-hangouts[8019]: event_continuation_token {
Jun 29 18:20:19 raspberrypi matrix-mautrix-hangouts[8019]: }
Jun 29 18:20:19 raspberrypi matrix-mautrix-hangouts[8019]: [2020-06-29 16:20:19,421] [DEBUG@hangups.http_utils] Sending request post https://clients6.google.com/chat/v1/conversations/getconversation:
Jun 29 18:20:19 raspberrypi matrix-mautrix-hangouts[8019]: b'LONGSTRING
Jun 29 18:20:34 raspberrypi matrix-mautrix-hangouts[8019]: [2020-06-29 16:20:34,374] [DEBUG@hangups.http_utils] Received response 200 OK:
Jun 29 18:20:34 raspberrypi matrix-mautrix-hangouts[8019]: b'LONGSTRING'
Jun 29 18:20:34 raspberrypi matrix-mautrix-hangouts[8019]: [2020-06-29 16:20:34,376] [DEBUG@hangups.client] Received Protocol Buffer response:
Jun 29 18:20:34 raspberrypi matrix-mautrix-hangouts[8019]: response_header {
Jun 29 18:20:34 raspberrypi matrix-mautrix-hangouts[8019]:   status: RESPONSE_STATUS_UNEXPECTED_ERROR
Jun 29 18:20:34 raspberrypi matrix-mautrix-hangouts[8019]:   error_description: "Unexpected error"
Jun 29 18:20:34 raspberrypi matrix-mautrix-hangouts[8019]:   current_server_time: 1593447619508000
Jun 29 18:20:34 raspberrypi matrix-mautrix-hangouts[8019]: }
Jun 29 18:20:34 raspberrypi matrix-mautrix-hangouts[8019]: [2020-06-29 16:20:34,378] [ERROR@mau.portal.TOKEN/ID] Failed to backfill portal
Jun 29 18:20:34 raspberrypi matrix-mautrix-hangouts[8019]: Traceback (most recent call last):
Jun 29 18:20:34 raspberrypi matrix-mautrix-hangouts[8019]:   File "/usr/lib/python3.8/site-packages/mautrix_hangouts/portal.py", line 271, in backfill
Jun 29 18:20:34 raspberrypi matrix-mautrix-hangouts[8019]:     await self._backfill(source, is_initial)
Jun 29 18:20:34 raspberrypi matrix-mautrix-hangouts[8019]:   File "/usr/lib/python3.8/site-packages/mautrix_hangouts/portal.py", line 277, in _backfill
Jun 29 18:20:34 raspberrypi matrix-mautrix-hangouts[8019]:     messages = await self._load_many_messages(source, is_initial)
Jun 29 18:20:34 raspberrypi matrix-mautrix-hangouts[8019]:   File "/usr/lib/python3.8/site-packages/mautrix_hangouts/portal.py", line 256, in _load_many_messages
Jun 29 18:20:34 raspberrypi matrix-mautrix-hangouts[8019]:     chunk, token = await self._load_messages(source, chunk_limit, token)
Jun 29 18:20:34 raspberrypi matrix-mautrix-hangouts[8019]:   File "/usr/lib/python3.8/site-packages/mautrix_hangouts/portal.py", line 230, in _load_messages
Jun 29 18:20:34 raspberrypi matrix-mautrix-hangouts[8019]:     resp = await source.client.get_conversation(hangouts.GetConversationRequest(
Jun 29 18:20:34 raspberrypi matrix-mautrix-hangouts[8019]:   File "/usr/lib/python3.8/site-packages/hangups/client.py", line 515, in get_conversation
Jun 29 18:20:34 raspberrypi matrix-mautrix-hangouts[8019]:     await self._pb_request('conversations/getconversation',
Jun 29 18:20:34 raspberrypi matrix-mautrix-hangouts[8019]:   File "/usr/lib/python3.8/site-packages/hangups/client.py", line 433, in _pb_request
Jun 29 18:20:34 raspberrypi matrix-mautrix-hangouts[8019]:     raise exceptions.NetworkError(
Jun 29 18:20:34 raspberrypi matrix-mautrix-hangouts[8019]: hangups.exceptions.NetworkError: Request failed with status 3: 'Unexpected error'
```

**Comment by hooger** [comment]
Another test. I restarted the bridge, with `initial_chat_sync: 0`It doesn't seems to be working. It seems that if `initial_chat_sync` is 0, but `initiali_limit` is not 0, than the bridge (or `hangups`?) does not like it: 
```
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]: [2020-06-30 13:53:37,237] [DEBUG@mau.user.@gergely:horvath.club] Syncing info of 22 puppets (avatars included: True)...                              
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]: [2020-06-30 13:53:37,479] [DEBUG@mau.user.@gergely:horvath.club] Fetching recent conversations to create portals for                                 
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]: [2020-06-30 13:53:37,480] [DEBUG@hangups.client] Sending Protocol Buffer request conversations/syncrecentconversations:                              
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]: request_header {                                                                                                                                     
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]:   client_version {
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]:     client_id: CLIENT_ID_WEB_HANGOUTS                                                                                                                
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]:     major_version: "hangups-0.4.10"                                                                                                                  
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]:   }
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]:   client_identifier {                                                                                                                                
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]:     resource: "lcsw_hangouts_29CED9C7"
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]:   }                                                                                                                                                  
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]:   language_code: "en"
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]: }
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]: max_conversations: 0
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]: max_events_per_conversation: 1
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]: sync_filter: SYNC_FILTER_INBOX
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]: [2020-06-30 13:53:37,481] [DEBUG@hangups.http_utils] Sending request post https://clients6.google.com/chat/v1/conversations/syncrecentconversations:
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]: b'\n2\n\x12\x08,\x1a\x0ehangups-0.4.10\x12\x18\n\x16lcsw_hangouts_29CED9C7"\x02en\x18\x00 \x01(\x01'
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]: [2020-06-30 13:53:37,646] [DEBUG@hangups.http_utils] Received response 200 OK:
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]: b'CigIAxIQVW5leHBlY3RlZCBlcnJvciCkkpXu8aTL1qcBKJjCooTYqeoC'
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]: [2020-06-30 13:53:37,647] [DEBUG@hangups.client] Received Protocol Buffer response:
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]: response_header {
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]:   status: RESPONSE_STATUS_UNEXPECTED_ERROR
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]:   error_description: "Unexpected error"
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]:   current_server_time: 1593525217567000
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]: }
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]: [2020-06-30 13:53:37,648] [ERROR@mau.user.@gergely:horvath.club] Failed to sync conversations and users
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]: Traceback (most recent call last):
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]:   File "/usr/lib/python3.8/site-packages/mautrix_hangouts/user.py", line 221, in on_connect_later
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]:     await self.sync()
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]:   File "/usr/lib/python3.8/site-packages/mautrix_hangouts/user.py", line 235, in sync
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]:     await asyncio.gather(self.sync_users(users), self.sync_chats(chats), loop=self.loop)
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]:   File "/usr/lib/python3.8/site-packages/mautrix_hangouts/user.py", line 275, in sync_chats
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]:     res = await self.client.sync_recent_conversations(hangouts.SyncRecentConversationsRequest(
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]:   File "/usr/lib/python3.8/site-packages/hangups/client.py", line 672, in sync_recent_conversations
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]:     await self._pb_request('conversations/syncrecentconversations',
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]:   File "/usr/lib/python3.8/site-packages/hangups/client.py", line 433, in _pb_request
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]:     raise exceptions.NetworkError(
Jun 30 15:53:37 matrix matrix-mautrix-hangouts[6671]: hangups.exceptions.NetworkError: Request failed with status 3: 'Unexpected error'
Jun 30 15:54:03 matrix matrix-mautrix-hangouts[6671]: [2020-06-30 13:54:03,147] [DEBUG@hangups.channel] Received chunk:
Jun 30 15:54:03 matrix matrix-mautrix-hangouts[6671]: b'17\n[[6,["noop"]\n]\n]\n'
Jun 30 15:54:03 matrix matrix-mautrix-hangouts[6671]: [2020-06-30 13:54:03,148] [DEBUG@hangups.channel] Chunk contains data array with id 6:
Jun 30 15:54:03 matrix matrix-mautrix-hangouts[6671]: ['noop']
Jun 30 15:54:03 matrix matrix-mautrix-hangouts[6671]: [2020-06-30 13:54:03,149] [DEBUG@hangups.event] Fired Event('Channel.on_receive_array')
Jun 30 15:54:28 matrix matrix-mautrix-hangouts[6671]: [2020-06-30 13:54:28,708] [DEBUG@hangups.channel] Received chunk:
Jun 30 15:54:28 matrix matrix-mautrix-hangouts[6671]: b'17\n[[7,["noop"]\n]\n]\n'
Jun 30 15:54:28 matrix matrix-mautrix-hangouts[6671]: [2020-06-30 13:54:28,709] [DEBUG@hangups.channel] Chunk contains data array with id 7:
Jun 30 15:54:28 matrix matrix-mautrix-hangouts[6671]: ['noop']
Jun 30 15:54:28 matrix matrix-mautrix-hangouts[6671]: [2020-06-30 13:54:28,710] [DEBUG@hangups.event] Fired Event('Channel.on_receive_array')
Jun 30 15:54:55 matrix matrix-mautrix-hangouts[6671]: [2020-06-30 13:54:55,039] [DEBUG@hangups.channel] Received chunk:
Jun 30 15:54:55 matrix matrix-mautrix-hangouts[6671]: b'17\n[[8,["noop"]\n]\n]\n'
Jun 30 15:54:55 matrix matrix-mautrix-hangouts[6671]: [2020-06-30 13:54:55,041] [DEBUG@hangups.channel] Chunk contains data array with id 8:
Jun 30 15:54:55 matrix matrix-mautrix-hangouts[6671]: ['noop']
Jun 30 15:54:55 matrix matrix-mautrix-hangouts[6671]: [2020-06-30 13:54:55,042] [DEBUG@hangups.event] Fired Event('Channel.on_receive_array')
```
These fired events are keep coming.

Settings `initial_limit` to 0 makes it fail the same way as before.

**Comment by hooger** [comment]
Now this is interesting! 

Current config:
```
    initial_chat_sync: 5                                                                                                                                                                                    
        initial_limit: 74                                                                                                                                                                                   
        missed_limit: 99 
```

What I see is this:
There is one request ending like this:
```
[2020-06-30 14:08:47,328] [INFO@hangups.conversation] Requesting conversations page 0
[2020-06-30 14:08:47,330] [DEBUG@hangups.client] Sending Protocol Buffer request conversations/syncrecentconversations:
request_header {
  client_version {
    client_id: CLIENT_ID_WEB_HANGOUTS
    major_version: "hangups-0.4.10"
  }
  client_identifier {
    resource: "lcsw_hangouts_TOKEN"
  }
  language_code: "en"
}
max_conversations: 100
max_events_per_conversation: 1
sync_filter: SYNC_FILTER_INBOX
sync_filter: SYNC_FILTER_ARCHIVED
[2020-06-30 14:08:47,332] [DEBUG@hangups.http_utils] Sending request post https://clients6.go...
```

then comes this:
```
[2020-06-30 14:08:48,478] [DEBUG@mau.user.@gergely:horvath.club] Syncing info of 22 puppets (avatars included: True)...
[2020-06-30 14:08:48,654] [DEBUG@mau.user.@gergely:horvath.club] Fetching recent conversations to create portals for
[2020-06-30 14:08:48,655] [DEBUG@hangups.client] Sending Protocol Buffer request conversations/syncrecentconversations:
request_header {
  client_version {
    client_id: CLIENT_ID_WEB_HANGOUTS
    major_version: "hangups-0.4.10"
  }
  client_identifier {
    resource: "lcsw_hangouts_TOKEN"
  }
  language_code: "en"
}
max_conversations: 5
max_events_per_conversation: 1
sync_filter: SYNC_FILTER_INBOX
[2020-06-30 14:08:48,657] [DEBUG@hangups.http_utils] Sending request post https://clients6.google.com/chat/v1/convers
```

Then comes this:
```
[2020-06-30 14:08:48,478] [DEBUG@mau.user.@gergely:horvath.club] Syncing info of 22 puppets (avatars included: True)...
[2020-06-30 14:08:48,654] [DEBUG@mau.user.@gergely:horvath.club] Fetching recent conversations to create portals for
[2020-06-30 14:08:48,655] [DEBUG@hangups.client] Sending Protocol Buffer request conversations/syncrecentconversations:
request_header {
  client_version {
    client_id: CLIENT_ID_WEB_HANGOUTS
    major_version: "hangups-0.4.10"
  }
  client_identifier {
    resource: "lcsw_hangouts_TOKEN"
  }
  language_code: "en"
}
max_conversations: 5
max_events_per_conversation: 1
sync_filter: SYNC_FILTER_INBOX
[2020-06-30 14:08:48,657] [DEBUG@hangups.http_utils] Sending request post https://clients6.google.com/...
```

which returns the 5 conversations, and then comes the population of the first room here:

```

[2020-06-30 14:08:49,057] [DEBUG@mau.user.@gergely:horvath.club] Server returned 5 conversations
[2020-06-30 14:08:49,057] [DEBUG@mau.user.@gergely:horvath.club] Syncing Ugwe2d-NkUnQaMsKEBN4AaABAQ
[2020-06-30 14:08:49,072] [DEBUG@mau.user.@gergely:horvath.club] Last message 7-H0Z7-FyJ49ASIemdOe8z in chat Ugwe2d-NkUnQaMsKEBN4AaABAQ not found in d
[2020-06-30 14:08:49,073] [DEBUG@mau.portal.Ugwe2d-NkUnQaMsKEBN4AaABAQ-114423729507355733668] Backfilling history through @gergely:horvath.club
[2020-06-30 14:08:49,073] [DEBUG@mau.portal.Ugwe2d-NkUnQaMsKEBN4AaABAQ-114423729507355733668] Fetching up to 99 messages through 114423729507355733668
[2020-06-30 14:08:49,074] [DEBUG@hangups.client] Sending Protocol Buffer request conversations/getconversation:
request_header {
  client_version {
    client_id: CLIENT_ID_WEB_HANGOUTS
    major_version: "hangups-0.4.10"
  }
  client_identifier {
    resource: "lcsw_hangouts_TOKEN"
  }
  language_code: "en"
}
conversation_spec {
  conversation_id {
    id: "ID"
  }
}
include_conversation_metadata: false
include_event: true
max_events_per_conversation: 99
[2020-06-30 14:08:49,076] [DEBUG@hangups.http_utils] Sending request post https://clients6.google.com/chat...
```

and after that the (now) regular infinte loop:

```
[2020-06-30 14:08:49,919] [DEBUG@hangups.client] Sending Protocol Buffer request conversations/getconversation:
request_header {
  client_version {
    client_id: CLIENT_ID_WEB_HANGOUTS
    major_version: "hangups-0.4.10"
  }
  client_identifier {
    resource: "lcsw_hangouts_TOKEN"
  }
  language_code: "en"
}
conversation_spec {
  conversation_id {
    id: "ID"
  }
}
include_conversation_metadata: false
include_event: true
max_events_per_conversation: 0
event_continuation_token {
  storage_continuation_token: "TOKEN
  event_timestamp: 1589825192313228
}
[2020-06-30 14:08:49,921] [DEBUG@hangups.http_utils] Sending request post https://clien...
```

Now what I see is that in the earlier requests there are `max_conversations` values. Is it possible that they are missing in the rest? Where can/should I add it in the code to test?
Thanks for the answer in advance!
